migrate.source.dir:
  type: migrate_source
  label: 'DIR'
  mapping:
    path:
      type: string
      label: 'A directory path'
    file_ext:
      type: string
      label: 'File type to search for'
    recurse:
      type: bool
      label: 'Recurse through provided directory'